// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT-YgOpI4cDy4x9fW9GpfwHJ47fVxYDoA',
    appId: '1:725704783303:web:f8c8385bb46dcd5161d5e2',
    messagingSenderId: '725704783303',
    projectId: 'everything-app-cc11c',
    authDomain: 'everything-app-cc11c.firebaseapp.com',
    storageBucket: 'everything-app-cc11c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD63T1Q6-NMabIgWltdgnSGqsfXuVhBbbY',
    appId: '1:725704783303:android:81508748d5d9169061d5e2',
    messagingSenderId: '725704783303',
    projectId: 'everything-app-cc11c',
    storageBucket: 'everything-app-cc11c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBto0OM5OdxZsVIlAQ41xwe3gGfWK-0stE',
    appId: '1:725704783303:ios:42d498030da2305461d5e2',
    messagingSenderId: '725704783303',
    projectId: 'everything-app-cc11c',
    storageBucket: 'everything-app-cc11c.appspot.com',
    iosClientId: '725704783303-102cu0o71loukbshr7da54u1sqmq409j.apps.googleusercontent.com',
    iosBundleId: 'com.example.everythingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBto0OM5OdxZsVIlAQ41xwe3gGfWK-0stE',
    appId: '1:725704783303:ios:42d498030da2305461d5e2',
    messagingSenderId: '725704783303',
    projectId: 'everything-app-cc11c',
    storageBucket: 'everything-app-cc11c.appspot.com',
    iosClientId: '725704783303-102cu0o71loukbshr7da54u1sqmq409j.apps.googleusercontent.com',
    iosBundleId: 'com.example.everythingApp',
  );
}
